{
  "version": 0.2,
  "phases": {
    "install": {
      "runtime-versions": {
        "python": 3.7
      }
    },
    "pre_build": {
      "commands": [
        "pipenv -v --python 3.6",
        "pipenv run pip install -r src/requirements.txt",
      ]
    },
    "build": {
      "commands": [
        "pipenv run python3 src/build.py"
      ]
    },
    "post_build": {
      "commands": [
        "mv src/out src/tmp_out",
        "mkdir -p src/out",
        "mv src/tmp_out \"src/out/$ROOT_OUT\""
      ]
    }
  },
  "artifacts": {
    "files": [
      "**/*"
    ],
    "base-directory": "src/out"
  }
}
